apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mcp-webstore.fullname" . }}-mcp-server
  labels:
    {{- include "mcp-webstore.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount.mcpServer }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mcp-webstore.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: mcp-server
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mcp-webstore.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: mcp-server
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mcp-webstore.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: mcp-server
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.mcpServer.repository }}:{{ .Values.image.mcpServer.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.mcpServer.pullPolicy }}
          ports:
            - name: http
              containerPort: 8001
              protocol: TCP
          env:
            - name: STORE_SERVER_URL
              value: {{ .Values.env.STORE_SERVER_URL | quote }}
          resources:
            {{- toYaml .Values.resources.mcpServer | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
