# docker-compose.yml
version: '3'

services:
  db:
    image: postgres:15
    container_name: postgresql
    restart: unless-stopped
    environment:
      POSTGRES_DB: ai_virtual_agent
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio
    container_name: minio
    restart: unless-stopped
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio_rag_user
      MINIO_SECRET_KEY: minio_rag_password
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data

  # Example backend service configuration for local development
  # backend:
  #   build: .
  #   container_name: ai-va-backend
  #   environment:
  #     DATABASE_URL: postgresql+asyncpg://admin:password@db:5432/ai_virtual_assistant
  #     LOCAL_DEV_ENV_MODE: true  # Enable auth bypass for local development
  #   ports:
  #     - '8080:8080'
  #   depends_on:
  #     - db

volumes:
  pgdata:
  minio_data:
