{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-dbstore.fullname" . }}-postgresql
  labels:
    {{- include "mcp-dbstore.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  postgres-password: {{ .Values.postgresql.auth.postgresPassword | b64enc | quote }}
  password: {{ .Values.postgresql.auth.password | b64enc | quote }}
  username: {{ .Values.postgresql.auth.username | b64enc | quote }}
  database: {{ .Values.postgresql.auth.database | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mcp-dbstore.fullname" . }}-mcp-server
  labels:
    {{- include "mcp-dbstore.labels" . | nindent 4 }}
    app.kubernetes.io/component: mcp-server
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  database-url: {{ printf "postgresql+asyncpg://%s:%s@%s-postgresql:5432/%s" .Values.postgresql.auth.username .Values.postgresql.auth.password (include "mcp-dbstore.fullname" .) .Values.postgresql.auth.database | b64enc | quote }}
{{- end }} 