apiVersion: v2
name: mcp-store-inventory
description: A Helm chart for Store Inventory MCP Server
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mcp
  - inventory
  - store
home: https://github.com/your-org/ai-virtual-agent
sources:
  - https://github.com/your-org/ai-virtual-agent
maintainers:
  - name: AI Virtual Agent Team
    email: team@example.com
