# Persona Configuration for AI Agents
# This file defines the available personas and their visual styling

personas:
  compliance_officer:
    label: "Compliance Officer"
    description: "Ensures adherence to banking regulations and compliance procedures"
    icon: "ShieldAltIcon"
    color: "red"
    className: "persona-compliance"
    avatarBg: "#dc2626"
    avatarIcon: "🛡️"
    gradient: "linear-gradient(135deg, #dc2626 0%, #b91c1c 100%)"
    borderColor: "#dc2626"
    
  relationship_manager:
    label: "Relationship Manager"
    description: "Handles lending requests and credit assessment"
    icon: "DollarSignIcon"
    color: "green"
    className: "persona-lending"
    avatarBg: "#059669"
    avatarIcon: "💰"
    gradient: "linear-gradient(135deg, #059669 0%, #047857 100%)"
    borderColor: "#059669"
    
  branch_teller:
    label: "Customer Service"
    description: "Assists with customer queries and account services"
    icon: "UserIcon"
    color: "blue"
    className: "persona-customer"
    avatarBg: "#2563eb"
    avatarIcon: "👥"
    gradient: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)"
    borderColor: "#2563eb"
    
  fraud_analyst:
    label: "Fraud Analyst"
    description: "Reviews alerts and investigates suspicious activities"
    icon: "EyeIcon"
    color: "orange"
    className: "persona-fraud"
    avatarBg: "#ea580c"
    avatarIcon: "🔍"
    gradient: "linear-gradient(135deg, #ea580c 0%, #c2410c 100%)"
    borderColor: "#ea580c"
    
  training_lead:
    label: "Training Lead"
    description: "Keeps staff current on regulations and certifications"
    icon: "BookIcon"
    color: "purple"
    className: "persona-training"
    avatarBg: "#7c3aed"
    avatarIcon: "📚"
    gradient: "linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)"
    borderColor: "#7c3aed"
    
  it_support:
    label: "IT Support"
    description: "Provides technical support for banking operations"
    icon: "CogIcon"
    color: "grey"
    className: "persona-it"
    avatarBg: "#6b7280"
    avatarIcon: "⚙️"
    gradient: "linear-gradient(135deg, #6b7280 0%, #4b5563 100%)"
    borderColor: "#6b7280"

# Default persona for unknown types
default:
  label: "AI Assistant"
  description: "General purpose AI assistant"
  icon: "CogIcon"
  color: "grey"
  className: "persona-default"
  avatarBg: "#6b7280"
  avatarIcon: "🤖"
  gradient: "linear-gradient(135deg, #6b7280 0%, #4b5563 100%)"
  borderColor: "#6b7280" 

# Replace the demo_questions section with workflow-based questions
demo_questions:
  default:
    - "What documents do I need to collect for a $500K small business loan application?"
    - "How do I calculate the debt service coverage ratio for this business loan?"
    - "What are the current SBA 7(a) loan requirements and processing times?"
    - "What's the next step after the loan is approved and how do I prepare closing documents?"
  
  compliance_officer:
    - "What are the current BSA/AML reporting requirements for cash transactions over $10,000?"
    - "How do I handle a customer who appears on the OFAC sanctions list?"
    - "What are the CFPB requirements for mortgage loan disclosures?"
    - "What's the process for filing a Suspicious Activity Report (SAR)?"
  
  relationship_manager:
    - "What documents do I need to collect for a $500K small business loan application?"
    - "How do I calculate the debt service coverage ratio for this business loan?"
    - "What are the current SBA 7(a) loan requirements and processing times?"
    - "What's the next step after the loan is approved and how do I prepare closing documents?"
  
  branch_teller:
    - "What's the process for opening a new business checking account for a sole proprietorship?"
    - "What customer identification documents are required for CIP compliance?"
    - "How do I handle a customer who wants to deposit $15,000 in cash today?"
    - "What are the daily transaction limits for this new business account?"
  
  fraud_analyst:
    - "I received an alert for suspicious activity - what are the first steps in investigation?"
    - "How do I determine if this transaction pattern indicates money laundering?"
    - "What information do I need to include when filing a SAR for this case?"
    - "What's the escalation process if this involves potential terrorist financing?"
  
  training_lead:
    - "What are the mandatory training requirements for new compliance officers this year?"
    - "How do I track completion of AML training for our branch staff?"
    - "What certifications are required for our lending officers and how do I verify them?"
    - "What's the process for updating training materials when new regulations are issued?"
  
  it_support:
    - "How do I grant system access to a new loan officer in the core banking platform?"
    - "What security protocols should I follow when setting up remote access for compliance staff?"
    - "How do I troubleshoot login issues with the fraud detection system?"
    - "What's the process for revoking access when an employee leaves the bank?" 