# Persona Configuration for AI Agents
# This file defines the available personas and their visual styling

personas:
  compliance_officer:
    label: "Compliance Officer"
    description: "Ensures adherence to banking regulations and compliance procedures"
    icon: "ShieldAltIcon"
    color: "red"
    className: "persona-compliance"
    avatarBg: "#dc2626"
    avatarIcon: "🛡️"
    gradient: "linear-gradient(135deg, #dc2626 0%, #b91c1c 100%)"
    borderColor: "#dc2626"
    
  relationship_manager:
    label: "Relationship Manager"
    description: "Handles lending requests and credit assessment"
    icon: "DollarSignIcon"
    color: "green"
    className: "persona-lending"
    avatarBg: "#059669"
    avatarIcon: "💰"
    gradient: "linear-gradient(135deg, #059669 0%, #047857 100%)"
    borderColor: "#059669"
    
  branch_teller:
    label: "Customer Service"
    description: "Assists with customer queries and account services"
    icon: "UserIcon"
    color: "blue"
    className: "persona-customer"
    avatarBg: "#2563eb"
    avatarIcon: "👥"
    gradient: "linear-gradient(135deg, #2563eb 0%, #1d4ed8 100%)"
    borderColor: "#2563eb"
    
  fraud_analyst:
    label: "Fraud Analyst"
    description: "Reviews alerts and investigates suspicious activities"
    icon: "EyeIcon"
    color: "orange"
    className: "persona-fraud"
    avatarBg: "#ea580c"
    avatarIcon: "🔍"
    gradient: "linear-gradient(135deg, #ea580c 0%, #c2410c 100%)"
    borderColor: "#ea580c"
    
  training_lead:
    label: "Training Lead"
    description: "Keeps staff current on regulations and certifications"
    icon: "BookIcon"
    color: "purple"
    className: "persona-training"
    avatarBg: "#7c3aed"
    avatarIcon: "📚"
    gradient: "linear-gradient(135deg, #7c3aed 0%, #6d28d9 100%)"
    borderColor: "#7c3aed"
    
  it_support:
    label: "IT Support"
    description: "Provides technical support for banking operations"
    icon: "CogIcon"
    color: "grey"
    className: "persona-it"
    avatarBg: "#6b7280"
    avatarIcon: "⚙️"
    gradient: "linear-gradient(135deg, #6b7280 0%, #4b5563 100%)"
    borderColor: "#6b7280"

# Default persona for unknown types
default:
  label: "AI Assistant"
  description: "General purpose AI assistant"
  icon: "CogIcon"
  color: "grey"
  className: "persona-default"
  avatarBg: "#6b7280"
  avatarIcon: "🤖"
  gradient: "linear-gradient(135deg, #6b7280 0%, #4b5563 100%)"
  borderColor: "#6b7280" 

# Demo questions are now loaded from template YAML files
# This ensures no hard-coded questions and allows for template-specific customization 