apiVersion: v2
name: mcp-dbstore
description: A Helm chart for MCP DBStore Server with integrated database
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - mcp
  - database
  - store
  - integrated
home: https://github.com/your-org/ai-virtual-agent
sources:
  - https://github.com/your-org/ai-virtual-agent
maintainers:
  - name: AI Virtual Agent Team
    email: team@example.com
dependencies:
  - name: postgresql
    version: "15.x.x"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
