name: Build and push image

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build-and-push:
    if: github.repository_owner == 'rh-ai-kickstart'
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: ai-virtual-assistant
            context: .
            chart: deploy/helm/ai-virtual-assistant/Chart.yaml
          - name: mcp_dbstore
            context: mcpservers/mcp_dbstore
            chart: deploy/helm/mcp-dbstore/Chart.yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}

      - name: Extract version from Chart.yaml
        id: version
        run: |
          version=$(grep '^appVersion:' ${{ matrix.chart }} | awk '{print $2}')
          echo "tag=$version" >> $GITHUB_OUTPUT

      - name: Build and push ${{ matrix.name }}
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.context }}
          file: ${{ matrix.context }}/Containerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: quay.io/ecosystem-appeng/${{ matrix.name }}:${{ steps.version.outputs.tag }}
